---
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.

- name: Create MOTD banner
  template: src=motd.j2 dest=/etc/motd mode=755

- name: Create file system
  file: "path={{ item }} state=directory"
  with_items:
    - "{{ install_dir }}"
    - "{{ data_dir }}"

- name: Download the distribution 
  get_url: "url={{ distribution_url }} dest={{ staging_dir }}/{{ distribution_archive }} mode=0444"

- name: Extract the distribution 
  command: "tar xzf {{ staging_dir }}/{{ distribution_archive }} --strip 1 -C {{ install_dir }}" 
 