# Directory in which all the files are generated
outputDirectory: target/

# Number Of donors that participated in the project (approximately 500 for a given project)
numberOfDonors: 500

# Number Of speciments per donor (ranges on average from 2 - 4)
numberOfSpecimensPerDonor: 4

# Number of samples per speciment (ranges on average from 2 - 4)
numberOfSamplesPerSpecimen: 4

# The lead jurisdiction of the project (refer to http://dcc.icgc.org/pages/docs/ICGC_Data_Submission_Manual-0.6c-150512.pdf appendix B)
leadJurisdiction: au

# The type of tumour (refer to http://dcc.icgc.org/pages/docs/ICGC_Data_Submission_Manual-0.6c-150512.pdf appendix B)
tumourType: 01

# The institution from which the results are produced (refer to http://dcc.icgc.org/pages/docs/ICGC_Data_Submission_Manual-0.6c-150512.pdf appendix B)
institution: 001

# The platform of the insitution (refer to http://dcc.icgc.org/pages/docs/ICGC_Data_Submission_Manual-0.6c-150512.pdf appendix B)
platform: 1

# This is to ensure consistent results across runs
seed: 1234567

# This is an array of all the optional files. Append/Unappend the array as necessary
#optionalFiles:
   # Name of the optional file
# - name: surgery
   # Number of lines for each entry in the donor file
 #  numberOfLinesPerDonor: 3
   # Name of the optional file
 #- name: exposure
   # Number of lines for each entry in the donor file
  # numberOfLinesPerDonor: 3
   # Name of the optional file
 #- name: family
   # Number of lines for each entry in the donor file
  # numberOfLinesPerDonor: 3
   # Name of the optional file
 #- name: biomarker
   # Number of lines for each entry in the donor file
  # numberOfLinesPerDonor: 3
   # Name of the optional file
 #- name: therapy
   # Number of lines for each entry in the donor file
  # numberOfLinesPerDonor: 3

# This is an array of all the experimental files. Append to the Array as necessary. Append in order (i.e. first meta, then primary, then secondary)
experimentalFiles:
   # Name of the experimental file
 - name: ssm
   # Type of the experimental file(meta (m), primary (p), secondary (s)) 
   fileType: m
   # Number of lines for each entry in the related file (e.g. 5 lines in the meta file per each sample entry in the sample file)
   numberOfLinesPerForeignKey: 3
 - name: ssm
   fileType: p
   # Approximately 2000 for a given project
   numberOfLinesPerForeignKey: 10
 - name: ssm
   fileType: s
   numberOfLinesPerForeignKey: 3
