---
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.

# Directories
install_dir: /srv/dcc-submission
web_dir: "{{ install_dir }}/www"
data_dir: "{{ install_dir }}/data"
bin_dir: "{{ install_dir }}/bin"
conf_dir: "{{ install_dir }}/conf"

# Distribution
dist_name: "dcc-submission-server"
dist_name_version: "{{ dist_name }}-{{ dist_version }}"
dist_archive: "{{ dist_name_version }}-dist.tar.gz"
dist_url: "{{ artifactory_release_url }}/org/icgc/dcc/{{ dist_name }}/{{ dist_version }}/{{ dist_archive }}"

# Shiro password utility
shiro_version: 1.2.1
shiro_url: "http://repo1.maven.org/maven2/org/apache/shiro/tools/shiro-tools-hasher/{{ shiro_version }}/shiro-tools-hasher-{{ shiro_version }}-cli.jar"