outputDirectory: target/
numberOfDonors: 7000
numberOfSpecimensPerDonor: 2
numberOfSamplesPerSpecimen: 2
leadJurisdiction: au
tumourType: 01
institution: 001
platform: 1	
seed: 1234567
experimentalFiles:
 - name: ssm
   fileType: m
   numberOfLinesPerForeignKey: 4
 - name: ssm
   fileType: p
   numberOfLinesPerForeignKey: 4
 - name: ssm
   fileType: s
   numberOfLinesPerForeignKey: 4
