---
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.

# The version of the dcc-submission-server to install
dist_version: 2.1.8

# Admin password for the submission system
admin_password: password