---
# Copyright 2016(c) The Ontario Institute for Cancer Research.

# The version of the reference genome to install
reference_genome_version: GRCh37

# Where to install the reference genome
target_dir: /tmp
