---
# Copyright 2013(c) The Ontario Institute for Cancer Research. All rights reserved.
#
# DCC Submission Server - Playbook 
#
# Description: 
#   The is the Ansible playbook file for provisioning the dcc-submission distribution.
#
# See:
#   - http://www.ansibleworks.com/docs/playbooks.html

- hosts: vagrant 
  sudo: yes
  roles: 
    - java
    - mongodb
    - server
    - reference
